name: Feature request
about: Suggest an idea for raglite
labels: enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
